language: java

dist: trusty
sudo: required

jdk:
- oraclejdk11

addons:
    sonarcloud:
        organization: "powsybl-ci-github"
        token:
            secure: ${SONAR_TOKEN}
        github_token:
            secure: ${GITHUB_TOKEN}

install:
# Build powsybl-core
- git clone https://github.com/powsybl/powsybl-core powsybl/powsybl-core
- pushd powsybl/powsybl-core && mvn -DskipTests install && popd

script:
- mvn clean verify sonar:sonar
